name: Matrix Strategy Example

on:
  workflow_dispatch:

jobs:
  test-ssl-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        uri:
          - 'https://badssl.com/'
          - 'https://mozilla-old.badssl.com/'
    steps:
      - name: Test SSL/TLS for ${{ matrix.uri }}
        uses: s01ipsist/test-ssl-action@main
        with:
          uri: ${{ matrix.uri }}
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testssl-results-${{ strategy.job-index }}
          path: testssl_results_*.json
